# Generated by Django 4.0.5 on 2022-06-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
