# Generated by Django 4.0.5 on 2022-06-30 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('users', '0002_tagsubscribed_usersubscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsubscribed',
            name='tag_subscribe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_tag', to='content.tag'),
        ),
    ]
