# Generated by Django 4.0.5 on 2022-06-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('users', '0003_alter_tagsubscribed_tag_subscribe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagSubscribed',
            new_name='TagSubscribtion',
        ),
        migrations.RenameModel(
            old_name='UserSubscribed',
            new_name='UserSubscribtion',
        ),
        migrations.AlterUniqueTogether(
            name='tagsubscribtion',
            unique_together={('user', 'tag_subscribe')},
        ),
    ]
