# Generated by Django 4.0.5 on 2022-07-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
